name: Equations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SwiftLint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.0

  Build-macOS:
    needs: SwiftLint

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  Build-iOS:
    needs: SwiftLint

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme Equations build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
      - name: Run tests
        run: xcodebuild -scheme Equations test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'